spring:
  main:
    banner-mode: off
    web-application-type: reactive
  application:
    name: blogify-app-api
  config:
    import:
    - classpath:META-INF/core.config.yaml
    - classpath:META-INF/ext.kakao.config.yaml
    - classpath:META-INF/ext.naver.config.yaml
    - classpath:META-INF/res.r2dbc.config.yaml
  aop:
    auto: true
    proxy-target-class: true
server:
  port: 8080
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false
    include-message: never
    include-stacktrace: never
    include-binding-errors: never
    include-exception: false

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: dev

---

spring:
  config:
    activate:
      on-profile: stg

---

spring:
  config:
    activate:
      on-profile: prod
