-- DROP TABLE IF EXISTS BLOG_SEARCH_WORD;
CREATE TABLE IF NOT EXISTS BLOG_SEARCH_WORD (
    SEQ      BIGINT   NOT NULL AUTO_INCREMENT,
    WORD     TEXT     NOT NULL,
    CNT      BIGINT   NOT NULL DEFAULT 0,
    REG_DTTM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (SEQ)
);

COMMENT ON  TABLE BLOG_SEARCH_WORD          IS '검색어';
COMMENT ON COLUMN BLOG_SEARCH_WORD.SEQ      IS '일련번호';
COMMENT ON COLUMN BLOG_SEARCH_WORD.WORD     IS '단어';
COMMENT ON COLUMN BLOG_SEARCH_WORD.CNT      IS '횟수';
COMMENT ON COLUMN BLOG_SEARCH_WORD.REG_DTTM IS '등록 일시';

CREATE INDEX IDX_BLOG_SEARCH_WORD_WORD ON BLOG_SEARCH_WORD(WORD);
CREATE INDEX IDX_BLOG_SEARCH_WORD_CNT  ON BLOG_SEARCH_WORD(CNT);
